### ISSUE TITLE
cannot compile due to pandoc-citeproc error

### ISSUE THREAD

**Issue by katrielalex** [tamarin-prover/manual-pandoc#1]
On Debian, make (or minimal example `pandoc --bibliography=src/manual.bib src/005_protocol-specification.md`) gives me a citeproc error:

```
> pandoc --bibliography=src/manual.bib src/005_protocol-specification.md 
pandoc-citeproc: "stdin" (line 9, column 2):
unexpected "i"
expecting "c", "C", "p", "P", "s" or "S"
pandoc: Error running filter pandoc-citeproc
```

This corresponds to the i of @inproceedings in the bibtex; Googling seems to indicate that @inproceedings isn't supported. Perhaps I have an old version of bibutils?

pandoc version = 1.12.2.1
pandoc-citeproc version = 0.2

**Comment by jdreier** [comment]
Fixed.
